# Generated by Django 5.2.7 on 2025-11-06 07:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Expense Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Expense Date')),
            ],
        ),
        migrations.RenameModel(
            old_name='Expense',
            new_name='OperativeExpense',
        ),
    ]
