# Generated by Django 5.2.7 on 2025-11-06 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_personalexpense_rename_expense_operativeexpense'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OperativeExpense',
            new_name='Expense',
        ),
        migrations.DeleteModel(
            name='PersonalExpense',
        ),
    ]
