# Generated by Django 5.2.7 on 2025-11-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_operativeexpense_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('Operative', 'Operative'), ('Personal', 'Personsl')], default='Operative', max_length=10),
        ),
    ]
