# Generated by Django 5.2.7 on 2025-11-07 15:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_expense_expense_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartingCapital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Expense Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Expense Date')),
                ('expense_type', models.CharField(max_length=10)),
            ],
        ),
    ]
