# Generated by Django 5.2.7 on 2025-11-07 15:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_startingcapital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startingcapital',
            name='expense_type',
        ),
        migrations.AlterField(
            model_name='startingcapital',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='startingcapital',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
    ]
